name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Format
      run: |
        go fmt ./...
        if [ -n "$(git status --porcelain)" ]; then
          echo "Go files need formatting"
          exit 1
        fi

    - name: Test
      run: go test -v ./...

    - name: Vet
      run: go vet ./...
